export type ContentBlock =
  | { type: 'text'; value: string }
  | { type: 'image'; value: string }
  | { type: 'heading'; value: string };

export type Article = {
  title: string;
  heroImage: string;
  content: ContentBlock[];
};

export const articles: Record<string, Article> = {
  '10427': {
    title: `鏢準情人｜命中愛情紅心`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1316-768x538-1.jpeg`,
    content: [
      { type: 'heading', value: `你有多久沒有心跳加速的感覺了？` },
      { type: 'text', value: `說真的，交友軟體滑到手痠，配對了一堆人卻只剩尬聊？好不容易約出來，結果兩個人坐在咖啡廳裡，你看我、我看你，空氣中只剩下攪拌咖啡的聲音......如果你也受夠了這種交友方式，那這場「鏢準情人」飛鏢聯誼，絕對會讓你眼睛一亮！` },
      { type: 'text', value: `飛鏢聯誼最棒的地方就是——不需要你口若懸河，光是一起瞄準、一起歡呼、一起吐槽彼此的「神奇射偏」就能自然破冰！你不用絞盡腦汁想話題，因為飛鏢就是最好的話題。當她幫你加油打氣、當你教她調整姿勢，那種自然產生的親近感，才是真正心動的開始。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2018/09/1316-1024x717.jpg` },
      { type: 'text', value: `想像一下這個畫面：特別設計的「加分、減分飛鏢賽」讓全場笑聲不斷，你和隊友一起歡呼、一起哀嚎，不知不覺就和旁邊的她聊開了。比賽結束，大家圍在一起慶祝，順手交換 LINE 就像呼吸一樣自然。很多參加過的學員都說：「這是我參加過最不尷尬的聯誼活動！」` },
      { type: 'text', value: `娜米跟你保證：每一位參加者都經過我們的嚴格審核，實名認證、身分把關，讓你安心認識每一個人。而且現場有專業主持人暖場帶動，就算你是「社恐」也不用怕，我們會幫你創造最自然的互動機會！` },
      { type: 'text', value: `別再等了！愛情不會自己飛到你面前，但飛鏢可以幫你命中紅心。立即私訊戀愛小秘書報名，讓我們一起鏢準你的幸福！` },
    ],
  },
  '66266': {
    title: `「干物女大變身」美膚彩妝造型班`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/ev_ecad1ceeec_1545037467-768x512-1.jpeg`,
    content: [
      { type: 'heading', value: `妳是不是也覺得「素顏見人好沒自信」？` },
      { type: 'text', value: `每天上班累成一條蟲，回到家只想躺平追劇，化妝？保養？哪有那個力氣！但偏偏，約會的邀約就這麼突然殺來了，打開化妝包才發現——粉底液過期了、眉筆不見了、眼影盤的顏色根本不適合自己......聽起來是不是很有既視感？` },
      { type: 'text', value: `心理學家馬布蘭提出「55/38/7 形象定律」——第一印象中，外在形象佔了高達 55%！《魅力學》也說：「給人留下好印象的機會只有一次。」但別擔心，這不是要你變成另一個人，而是讓專業彩妝師幫你找到「最適合你的樣子」。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'text', value: `在這堂造型班裡，專業彩妝師會手把手教你：怎麼根據自己的臉型和膚質選擇妝容、如何用最簡單的步驟打造氣色滿分的日常妝、還有當季最流行的彩妝技巧。最重要的是，你會發現原來「變美」沒有想像中那麼難！很多學員上完課後都說：「天啊，原來我可以這麼好看！」` },
      { type: 'text', value: `娜米悄悄跟你說：這堂課不只是學化妝，更是幫你找回自信的秘密武器。當你對鏡子裡的自己微笑時，那份自信，才是讓異性怦然心動的關鍵。我們嚴選的彩妝師都是業界頂尖，絕對讓你值回票價！` },
      { type: 'text', value: `準備好讓自己煥然一新了嗎？名額有限，手刀私訊戀愛小秘書報名吧！讓最美的妳，遇見最對的人。` },
    ],
  },
  '83508': {
    title: `桌遊派對遊戲`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/10379865_385912448249347_2126902594935315737_o-960x540-1.jpeg`,
    content: [
      { type: 'heading', value: `聯誼最怕什麼？就是兩個人乾坐在那裡大眼瞪小眼！` },
      { type: 'text', value: `傳統聯誼的噩夢你一定經歷過：對面坐了一個人，你拼命想話題，對方也在拼命想話題，結果兩個人聊了半小時的天氣和工作，然後......就沒有然後了。但桌遊聯誼完全不一樣！當你們為了贏得比賽絞盡腦汁、為了一張牌爭得面紅耳赤、為了隊友的神操作拍桌大笑——誰還記得這是一場「聯誼」？` },
      { type: 'text', value: `這就是桌遊的魔力：它讓你在最放鬆、最真實的狀態下認識對方。你會看到她認真思考時微微皺眉的樣子，他出奇制勝時得意的笑容，這些都是坐在咖啡廳裡永遠看不到的。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_c4838b2994_1519733922-1024x512.jpg` },
      { type: 'text', value: `現場備有無限量供應的飲料和小點心，還有專業主持人帶你快速上手遊戲規則，完全不用擔心「我不會玩怎麼辦」。從破冰遊戲到策略桌遊，每個環節都經過精心設計，讓你們在歡笑中自然熟絡。遊戲結束還有小獎品，贏的人開心，輸的人也不虧——因為你贏得的是一群志同道合的新朋友！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'text', value: `娜米保證：我們的參加者都經過嚴格篩選，素質有保障。現場氣氛輕鬆到你會忘記緊張，只記得笑到肚子痛！很多學員參加完都意猶未盡地問：「下一場什麼時候？」` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f567e1223d_1521796535-1024x683.jpg` },
      { type: 'text', value: `別讓「不好意思」成為你單身的理由。立即私訊戀愛小秘書報名，一起在桌遊中找到你的「最佳拍檔」！` },
    ],
  },
  '83509': {
    title: `鐳射槍與漆彈`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1.png`,
    content: [
      { type: 'heading', value: `交友不想只是吃飯聊天？來點刺激的吧！` },
      { type: 'text', value: `老實說，你是不是也覺得傳統聯誼太無聊了？吃飯、聊天、交換 LINE，然後回家發現根本不知道對方是什麼樣的人。但如果你們一起在戰場上並肩作戰、互相掩護、一起歡呼勝利呢？那種腎上腺素飆升的感覺，會讓你在最短時間內看到對方最真實的一面！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/event01-1024x1024.jpg` },
      { type: 'text', value: `「鐳射漆彈｜六度空間 逃出生天」結合了鐳射槍戰和密室逃脫的元素，分組後你們要一起解謎、一起作戰。當你為了保護隊友裡的她而英勇衝鋒，當她在關鍵時刻找到通關線索，那種革命情感，比吃十頓飯都有效！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/186514-768x1024.jpg` },
      { type: 'text', value: `不管你是遊戲高手還是新手小白都沒關係！重點不是你的射擊技術有多準，而是你們在過程中的互動——一個眼神、一次配合、一句「小心後面！」就能拉近彼此的距離。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/36dea3b8-261c-449b-9dd3-dd6a93ae9411-1024x1024.jpg` },
      { type: 'text', value: `娜米掛保證：活動全程有專業教練指導，安全無虞。參加者都是經過我們嚴格審核的優質單身男女，讓你玩得開心、交友放心。而且啊，在槍林彈雨中培養出的默契，可是比任何約會都來得深刻呢！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/606e84c3-9f60-498c-87b1-856bb85c7dd1.png` },
      { type: 'text', value: `準備好逃出單身的「密室」了嗎？立即私訊戀愛小秘書報名，一起來場最刺激的脫單冒險！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/f96896ea7ec309a3c3e68aa13455d6fa-1024x733.png` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/帶按鈕圖-情境圖-女生-婚友02.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/帶按鈕圖-情境圖-女生-對比弱02.jpg` },
    ],
  },
  '83510': {
    title: `浪漫石門放風箏`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/w600h600r16888.jpeg`,
    content: [
      { type: 'heading', value: `整天關在辦公室，你有多久沒有深呼吸了？` },
      { type: 'text', value: `工作忙到沒時間交朋友，好不容易放假卻只想宅在家。想出去走走，但一個人去哪裡都覺得尷尬......聽起來是不是就是你的日常？如果有一個活動，能讓你在美麗的海岸線旁放鬆身心，又能自然認識志同道合的異性朋友，你願不願意給自己一次機會？` },
      { type: 'text', value: `石門草坪是北海岸最美的秘境之一，秋風徐徐，天空湛藍。我們要在這裡一起放風箏！想像一下：你和她一起拉著風箏線，風吹亂了頭髮，你們相視而笑，那畫面比偶像劇還浪漫。草坪上我們還精心佈置了野餐點，準備了咖啡和小點心，讓你們在最輕鬆的氛圍下聊天認識。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_92694ede50_1435644107-1024x687.jpg` },
      { type: 'text', value: `這場活動的魅力在於：你不需要刻意表現，大自然就是最好的氣氛製造師。迎著海風跑起來的時候，誰還會緊張呢？放風箏的過程需要兩個人配合，這種不經意的「身體靠近」和「默契培養」才是真正的破冰神器。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/QJ8579085321.jpeg` },
      { type: 'text', value: `娜米溫馨提醒：我們的戶外活動都有完善的規劃和安全保障，每位參加者都經過實名認證。穿著舒適的衣服和好走的鞋子就好，我們會幫你安排好一切！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/1660792332-364008c565a2b14a6ee1f14ffe6ff029-1024x576.jpg` },
      { type: 'text', value: `秋天的風正好，你的幸福也剛剛好。別讓美好的季節溜走，立即私訊戀愛小秘書報名吧！` },
    ],
  },
  '83511': {
    title: `密室逃脫聯誼`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/I3HFCBUPA67NZ0A_N.png`,
    content: [
      { type: 'heading', value: `想脫單？先從「逃脫」開始！` },
      { type: 'text', value: `你是不是也有這種困擾：跟陌生人聊天超級彆扭，明明想認識對方卻不知道從何開口？傳統聯誼的那種「輪流自我介紹」更是讓你手心冒汗......但密室逃脫不一樣！一進密室，你根本來不及緊張，因為倒數計時已經開始了！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_73c0259d52_1465025125-1024x578.jpg` },
      { type: 'text', value: `想像這個場景：你和她被分到同一組，密碼鎖就在眼前，線索散落一地。「你看這個紙條上寫什麼？」「等等，我覺得這個數字有關聯！」不知不覺，你們已經在討論、在合作、在大笑，完全忘了十分鐘前你們還是陌生人。這就是密室逃脫的魔力——讓你們在共同的目標中自然熟絡！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/event01-1024x1024.jpg` },
      { type: 'text', value: `而且在解謎過程中，你可以看到對方最真實的一面：她遇到難題時的專注、他找到線索時的興奮、大家一起倒數最後十秒的緊張——這些共同經歷會讓你們的關係比一般聯誼深刻十倍！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/@6IR9W2UG8LGZ1MOR-300x159.png` },
      { type: 'text', value: `娜米保證：不管你是解謎高手還是第一次玩，都能享受其中。我們會根據大家的程度安排適合的密室，而且每一位參加者都經過嚴格身分審核，讓你安心投入每一場冒險！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/20221030220028_19371-300x205.png` },
      { type: 'text', value: `別再一個人面對「單身」這道謎題了，讓我們一起破關！立即私訊戀愛小秘書報名，你的脫單冒險從這裡開始！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/帶按鈕圖-情境圖-女生-婚友04.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/帶按鈕圖-情境圖-女生-對比弱01.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/帶按鈕圖-情境圖-女生-對比弱03.jpg` },
    ],
  },
  '83517': {
    title: `手工製作玫瑰蘋果塔`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/20231014手作蘋果塔-768x475-1.jpeg`,
    content: [
      { type: 'heading', value: `一個人吃甜點很療癒，兩個人做甜點才叫幸福！` },
      { type: 'text', value: `七夕過了、中秋過了，眼看又要到年底了，你的身邊還是只有一個人嗎？與其在家滑手機羨慕別人的放閃照，不如給自己一個機會，用一場甜蜜的手作體驗來開啟新的邂逅！` },
      { type: 'text', value: `手作蘋果塔的過程就是最自然的破冰方式！你們得一起切蘋果、一起揉麵團、一起擠奶油，手忙腳亂的時候她幫你遞工具、你幫她擦掉臉上的麵粉——這些小互動，比聊一百句「你興趣是什麼」都來得有感覺。而且不管你是烘焙高手還是廚房小白，都能玩得開心，因為有專業主廚在旁邊 carry 你！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/20231014手作蘋果塔-1024x634.jpg` },
      { type: 'text', value: `現場有舒適的廚藝教室、優質的食材、還有專業主廚手把手教學。你只需要帶著好心情來就好，我們幫你準備一切！從認識破冰、一起動手做甜點，到最後的聯誼互動時間，每個環節都讓你自然又輕鬆地認識身邊的人。` },
      { type: 'text', value: `娜米想對你說：做甜點就像談戀愛，需要耐心、需要溫度，更需要那個願意跟你一起等待的人。我們嚴格把關每一位參加者的身分和素質，讓你在最安心的環境下遇見對的人。` },
      { type: 'text', value: `名額有限，錯過這次要再等很久！立即私訊戀愛小秘書報名，一起做出屬於你們的甜蜜回憶吧！` },
    ],
  },
  '83518': {
    title: `溯溪聯誼活動`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/tn_P5210561-678x509-1.jpeg`,
    content: [
      { type: 'heading', value: `想快速跟人熟起來，又不想只是坐著聊天？` },
      { type: 'text', value: `每次聯誼都是咖啡廳、餐廳、KTV，膩了嗎？想要來點不一樣的？溯溪聯誼就是你的最佳選擇！在清涼的溪水中，你和她一起攀岩、一起跳水、互相扶持走過濕滑的石頭——這種「患難見真情」的經歷，會讓你們瞬間變得超級熟！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/01/163749-1024x576.jpg` },
      { type: 'text', value: `你可能會想：「我怕水怎麼辦？」「我體力不好可以嗎？」完全不用擔心！全程都有專業教練陪同，而且路線經過精心規劃，就算是新手也能安全享受。重點是，當你鼓起勇氣跳下那個小瀑布的時候，她在岸邊為你加油歡呼的那一刻——相信我，那種感覺比什麼告白都浪漫！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_48d0abc356_1495678078-1024x728.jpg` },
      { type: 'text', value: `娜米的貼心叮嚀：溯溪活動我們都有投保、有專業裝備、有經驗豐富的教練。每位參加者都是經過嚴格審核的優質單身男女。你只需要準備好一顆冒險的心，剩下的交給我們就好！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/S__154296461-725x1024.jpg` },
      { type: 'text', value: `還在等什麼？夏天就是要玩水、就是要脫單！立即私訊戀愛小秘書報名，一起在溪水中沖出你的愛情吧！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/tn_P5210561.jpg` },
    ],
  },
  '84852': {
    title: `貓咪咖啡廳｜喵星人派對`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/e6f15b6e34b04f5fa7fde12cbd2e453d.jpeg`,
    content: [
      { type: 'heading', value: `比起跟人尬聊，你是不是更想跟貓說話？` },
      { type: 'text', value: `如果你也是那種「跟貓比跟人自在」的人，那這場活動根本就是為你量身打造！很多人害怕聯誼的原因就是：不知道跟陌生人聊什麼。但有了貓咪當「僚機」，一切都不一樣了——「你看牠好可愛！」「牠好像喜歡你耶！」光是討論貓咪就能聊上一整天！` },
      { type: 'text', value: `在溫馨的貓咪咖啡廳裡，你們一邊享用精緻套餐，一邊擼貓，一邊自然地認識彼此。當你們一起蹲下來逗弄同一隻貓、一起被牠翻肚子萌到尖叫的時候，那種共同的小幸福，會讓兩個陌生人瞬間變成「貓友」，然後也許就變成......更特別的關係。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'text', value: `娜米想跟你說一個秘密：觀察一個人對待動物的方式，就能看出他是不是一個溫柔的人。這場活動不只是讓你認識新朋友，更讓你在最自然的情境下看到對方最柔軟的一面。而且我們嚴格把關參加者素質，讓你放心交流！` },
      { type: 'text', value: `愛貓的你，值得遇見一個同樣愛貓的人。立即私訊戀愛小秘書報名，和喵星人一起為你牽紅線！` },
    ],
  },
  '84854': {
    title: `戀愛講座：排約或約會，高手會怎麼做？`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/d1201119.jpeg`,
    content: [
      { type: 'heading', value: `約會前一天，你是不是緊張到睡不著？` },
      { type: 'text', value: `好不容易約到心儀的對象了，結果約會當天腦袋一片空白：穿什麼好？聊什麼話題？去哪裡吃飯？要不要牽手？一個問題接一個問題，緊張到手心冒汗......你知道嗎？大部分的約會失敗，不是因為你不夠好，而是因為你「不知道怎麼做」！` },
      { type: 'text', value: `這堂戀愛講座，我們特別邀請了 54 愛情學苑的人氣博主——派特，來教你「高手都怎麼約會」！從約會前的準備、第一印象的經營、到話題的引導和氛圍的營造，所有你想問卻不好意思問的問題，派特老師都會一一為你解答。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/344769750_1175439030520947_2939810061079920983_n-768x1024.jpg` },
      { type: 'text', value: `娜米知道，學會約會技巧，等於掌握了幸福的鑰匙。不管你是完全沒經驗的約會新手，還是想要更上一層樓的戀愛學生，這堂課都會讓你收穫滿滿。而且我們的講座環境溫馨、氛圍輕鬆，你可以安心提問、盡情學習。` },
      { type: 'text', value: `下一次約會，你可以不再手足無措。立即私訊戀愛小秘書報名，讓專業的來幫你的愛情加分！` },
    ],
  },
  '84855': {
    title: `FUEGO巧克力傳情`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/ev_8c0723be28_1445396497-768x509-1.jpeg`,
    content: [
      { type: 'heading', value: `一年又要過了，你的身邊還是只有巧克力陪你？` },
      { type: 'text', value: `街上成雙成對的情侶讓你看了直翻白眼？冬天到了特別想有個人牽手取暖？與其在家追劇吃零食，不如來一場巧克力味的浪漫邂逅！在 FUEGO 時尚餐廳裡，你不只能品嚐頂級巧克力，還能遇見那個讓你心融化的人。` },
      { type: 'text', value: `活動精心設計了巧克力調酒品鑑、愛情配對遊戲和心理測驗破冰環節。在微醺的氛圍中，你們一起品嚐達人調製的巧克力調酒，一起參與有趣的互動遊戲。巧克力的甜、調酒的微醺、她的笑容——三重攻擊，誰受得了？` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/b8a62d028c89fe1d4b6c307f61edd073-1024x683.jpg` },
      { type: 'text', value: `活動尾聲，在星空下一邊品味巧克力、一邊和新認識的她聊聊心事，FUEGO 的優雅氛圍幫你把浪漫值拉滿。很多學員都說這是他們參加過最有「氛圍感」的聯誼活動！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/hgCYXV-vGJsR1cum3kMGjInSLE1MK2RW2j_U9QIzZbt3FBJMSLaCv8bY782i7uhfjoJrvItByyS4HHaWdXyO_DrXIaWutJls2xCVbatkhjUNNiIYVnHvzugZCuBITtvjski7YaLlHpkrQUr5euoQrg.jpg` },
      { type: 'text', value: `娜米掛保證：FUEGO 的餐點精緻、環境一流，參加者都經過嚴格審核。你只需要帶著一顆期待的心來，我們幫你把場景、氛圍、對象都安排到位！` },
      { type: 'text', value: `別讓巧克力只是巧克力，讓它成為你愛情的開始。立即私訊戀愛小秘書報名，你的甜蜜冬日從這裡開始！` },
    ],
  },
  '84856': {
    title: `一對一精緻客製化專屬約會`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/ev_d92c8926ce_1555391132.jpeg`,
    content: [
      { type: 'heading', value: `團體活動太吵、太亂、不知道該注意誰？` },
      { type: 'text', value: `參加大型聯誼的時候，你是不是常常有這種感覺：人太多了，還沒來得及好好認識一個人，活動就結束了。或是好不容易遇到一個不錯的，卻沒有機會深入聊天......如果你渴望的是「有品質的認識」而不是「有數量的交換名片」，一對一客製化約會絕對是你的首選！` },
      { type: 'text', value: `戀愛小秘書會根據你的喜好、條件和需求，幫你精心安排最合適的約會對象。從約會的地點、時間到話題引導，我們都幫你規劃好了。你只需要坐下來，享用精緻下午茶，和眼前這個人好好聊聊天就好。我們還貼心準備了「話題製造機」，讓你完全不用擔心冷場！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/event01-1024x1024.jpg` },
      { type: 'text', value: `娜米的私房保證：每一個配對都是我們團隊用心安排的結果。我們會先深度訪談你，了解你真正在乎的特質和需求，再結合我們的人格分析測驗和數據配對，為你找到最有可能的「對的人」。配對成功率超高，這就是我們的自信！` },
      { type: 'text', value: `緣分不等人，你的另一半也許正在等你。立即私訊戀愛小秘書，讓我們為你安排一場專屬的浪漫約會！` },
    ],
  },
  '84857': {
    title: `美味鮭魚｜品味愛情的美妙滋味！`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/ev_cd416212ab_1450500908-768x512-1.jpeg`,
    content: [
      { type: 'heading', value: `想抓住他的心？先抓住他的胃！` },
      { type: 'text', value: `你是不是也覺得每次約會吃飯，兩個人只是各吃各的，氣氛超級尷尬？但如果是「一起做飯」呢？想像一下：你們圍在同一個料理台前，他幫你切蔬菜、你幫他調味，兩個人手忙腳亂卻笑聲不斷——這種互動，比坐在餐廳裡正襟危坐有趣一百倍！` },
      { type: 'text', value: `在專業大廚的帶領下，就算你是廚房菜鳥也能輕鬆上手。一邊學做鮭魚料理、一邊和身邊的人自然聊天，美食的香氣就是最好的話題催化劑。而且一起完成一道料理的成就感，會讓你們瞬間拉近距離！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'text', value: `娜米跟你說實話：料理聯誼一直是我們最受歡迎的活動之一，每次名額都秒殺！因為美食+互動的組合，真的讓人零壓力就能交到朋友。參加者都是經過我們嚴格審核的優質單身男女，讓你吃得開心、聊得安心。` },
      { type: 'text', value: `美味不等人，愛情也是。立即私訊戀愛小秘書報名，一起料理出你的幸福好味道！` },
    ],
  },
  '84858': {
    title: `和風創意｜壽司DIY`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/275113f2cb61f4c3b4bc6d3edcb1248e.jpeg`,
    content: [
      { type: 'heading', value: `平常只會叫外賣？來學一招讓異性刮目相看！` },
      { type: 'text', value: `會做壽司的人，在約會市場上根本就是大加分！但重點不是你做得多好，而是「一起動手做」的過程有多好玩。兩個人一起選食材、一起鋪飯、一起捲壽司，捲歪了還能互相吐槽，這種自然的互動才是最棒的破冰方式！` },
      { type: 'text', value: `現場有專業壽司師傅手把手教學，從選材到裝飾，讓你感受滿滿的和風創意。你可以發揮想像力，打造獨一無二的壽司作品——說不定你做的「創意壽司」就成了你們之間的第一個笑話和回憶呢！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/275113f2cb61f4c3b4bc6d3edcb1248e.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_47998ab817_1437375021-480x1024.jpg` },
      { type: 'text', value: `娜米保證：這場活動輕鬆有趣、零壓力，不管你是料理新手還是壽司達人都能玩得盡興。所有參加者都經過實名認證和嚴格篩選，讓你在享受美食的同時安心交友。` },
      { type: 'text', value: `想要一場不一樣的邂逅嗎？立即私訊戀愛小秘書報名，和你的命中注定一起捲出幸福！` },
    ],
  },
  '84859': {
    title: `K歌派對-歌聲傳情`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/event03.jpeg`,
    content: [
      { type: 'heading', value: `平常洗澡唱歌只有蓮蓬頭聽到？是時候換個觀眾了！` },
      { type: 'text', value: `不擅長聊天沒關係，會唱歌就是你的超級武器！K歌聯誼最棒的地方就是：不用想話題，點一首歌就是最好的自我介紹。當你用歌聲打動全場，隔壁的她眼裡閃著星光看你的時候——那個瞬間，值了！` },
      { type: 'text', value: `活動中我們精心安排了情歌對唱環節和趣味小遊戲，讓你和她有機會「合唱」一首歌。不管你是實力派歌手還是歡樂派音痴，這裡只有歡笑沒有評分！麥克風就是你的告白道具，歌聲就是最溫柔的搭訕。現場還有無限量的美味小點心和飲料，讓你在歡唱之間補充能量！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_7744a91aca_1466154992-1024x576.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f7178a62ac_1545731012-1024x806.png` },
      { type: 'text', value: `娜米跟你保證：K歌派對的氣氛嗨到你根本忘記緊張！所有參加者都經過嚴格審核，帥哥美女雲集。在歡樂的歌聲中，你會發現認識新朋友原來這麼簡單。` },
      { type: 'text', value: `下一首歌，為你的幸福而唱。立即私訊戀愛小秘書報名，用歌聲找到你的知音人！` },
    ],
  },
  '84860': {
    title: `型男培養講堂：如何培養迷人的個性`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/2.jepg_-2048x1600.jpg`,
    content: [
      { type: 'heading', value: `為什麼條件不差的你，女生就是對你沒感覺？` },
      { type: 'text', value: `工作穩定、收入不錯、長相也不差，但每次約會完女生就消失了？問題可能不在你的「條件」，而在你的「個性表達」。很多男生不是不好，只是不知道怎麼讓女生「感受到」你的好。這堂課就是要幫你找到答案！` },
      { type: 'text', value: `我們特別邀請專家來深度剖析：什麼樣的人格特質最受女生青睞？幽默感怎麼培養？自信怎麼展現？如何讓你的「性格」成為吸引力的來源？這些都不是天生的，而是可以學習和練習的！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_df87dba25a_1456821227-1024x683.jpg` },
      { type: 'text', value: `娜米以過來人的身分告訴你：我們成功配對超過 4000 位男女，最受歡迎的男生不一定最帥、最有錢，但他們都有一個共同點——「讓人相處起來很舒服的個性」。這堂課會教你怎麼成為那樣的人。` },
      { type: 'text', value: `改變從一堂課開始。立即私訊戀愛小秘書報名，讓最好的你去遇見最好的她！` },
    ],
  },
  '84862': {
    title: `綠意盎然｜多肉植物DIY`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/BHWQOX46V746ZQS.png`,
    content: [
      { type: 'heading', value: `想養貓養狗卻怕麻煩？那就從養多肉開始吧——順便養個感情！` },
      { type: 'text', value: `多肉植物有個特點：它很療癒、很可愛、而且超好養。就像這場聯誼活動——輕鬆、有趣、零壓力。如果你害怕那種「正式感」很重的聯誼場合，多肉 DIY 絕對會讓你改觀！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/BHWQOX46V746ZQS.png` },
      { type: 'text', value: `從老師教大家認識不同品種的多肉植物開始，到自己動手組盆、選土、種植，每個環節都充滿驚喜和交流。當你們一起蹲在桌前，小心翼翼地為多肉挑選最美的位置，那種專注又溫柔的氛圍，會讓你自然而然想跟身邊的人多聊幾句。活動結束，你還能把親手做的多肉帶回家——每次看到它，就會想起那天認識的人。` },
      { type: 'text', value: `娜米貼心提醒：這場活動就像多肉植物一樣——不需要太多華麗的包裝，真實自然就是最好的樣子。我們嚴格把關參加者素質，讓你在最舒服的狀態下認識新朋友。` },
      { type: 'text', value: `讓愛像多肉一樣慢慢生長。立即私訊戀愛小秘書報名，種下你的幸福種子！` },
    ],
  },
  '84863': {
    title: `夕陽情懷｜淡水河畔騎車趣`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/P-1521774-DFFDB604O-768x512-1.jpeg`,
    content: [
      { type: 'heading', value: `上一次看夕陽是什麼時候？身邊有人一起看嗎？` },
      { type: 'text', value: `每天通勤、加班、回家倒頭就睡，你的生活是不是只剩下工作和睡覺？淡水河畔的夕陽那麼美，一個人看太浪費了。跟一群志同道合的人一起騎自行車、一起看夕陽、一起吹河風——光想就覺得幸福！` },
      { type: 'text', value: `沿著河畔騎車，微風拂過臉龐，陽光灑在水面上波光粼粼。你和她並肩騎著車，不用刻意找話題，光是一起享受這份美好就夠了。中途停下來玩個小遊戲、吃個點心，不知不覺就聊開了。當夕陽把河面染成金黃色的時候，記得拍一張合照——這可能就是你們故事的起點。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/03/event03-150x150.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'text', value: `娜米保證：我們的戶外活動路線安全、規劃完善，全程有工作人員陪同。參加者都經過嚴格審核，讓你在最美的風景中遇見最對的人。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_ecbfd5e3b9_1546591688-1024x640.jpg` },
      { type: 'text', value: `最美的風景要跟對的人一起看。立即私訊戀愛小秘書報名，在夕陽下開始你的浪漫故事！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f567e1223d_1521796535-1024x683.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/event01-1024x1024.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/P-1521774-DFFDB604O-1024x682.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/88d5472e926dcd6bf913b0af5195e88b_%E5%89%AF%E6%9C%AC_%E5%89%AF%E6%9C%AC-150x150.png` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/MTXX_MH20230805_211553766.jpg` },
    ],
  },
  '84864': {
    title: `愜意情調｜滿天星花賞夜趣`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/88d5472e926dcd6bf913b0af5195e88b_副本_副本-687x1024-1.png`,
    content: [
      { type: 'heading', value: `城市的夜空看不到星星，但我們幫你找到另一種浪漫。` },
      { type: 'text', value: `加班到深夜、擠進捷運、回到空蕩蕩的家......你有多久沒有停下來，好好感受生活的美好了？如果有一場活動，能讓你遠離繁忙，在落花小徑上漫步，在星光下品嚐小點心，還能認識和你一樣渴望慢下來的人——你會不會心動？` },
      { type: 'text', value: `「滿天星花賞夜趣」就是這樣一場讓人放鬆到不行的活動。走在灑滿花瓣的小徑上，空氣中飄著淡淡花香，天色漸暗後，螢火蟲般的點點燈光在身邊閃爍。你和她肩並肩走著，不需要刻意找話題，因為這份浪漫的氛圍就是最好的媒介。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/12121.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/2cdd2d70f60c8bb07ad6e5cf8b0ec2ab-1024x620.jpeg` },
      { type: 'text', value: `娜米的溫暖叮嚀：在最美的場景中，你只需要做最真實的自己。我們精心佈置了每一個細節，從路線到點心到燈光，就是為了讓你在最舒服的狀態下認識新朋友。每位參加者都經過嚴格的實名認證和身分審核。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/88d5472e926dcd6bf913b0af5195e88b_副本_副本-687x1024.png` },
      { type: 'text', value: `生活已經夠辛苦了，你值得一個浪漫的夜晚。立即私訊戀愛小秘書報名，讓我們一起在星光下邂逅幸福！` },
    ],
  },
  '84865': {
    title: `療癒的浪漫小物｜浮游花手作趣`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1697009498737.jpeg`,
    content: [
      { type: 'heading', value: `上班壓力大到想尖叫？來做點療癒的事吧！` },
      { type: 'text', value: `每天被工作追著跑，好不容易有個假日卻不知道要幹嘛。一個人逛街無聊、一個人看電影心酸......如果有一場活動，能讓你在咖啡香氣中放鬆身心，親手創造一個美麗的浮游花作品，還能順便認識一群有趣的人——這不就是完美的週末嗎？` },
      { type: 'text', value: `浮游花手作的過程超級療癒：挑選自己喜愛的花色、一片一片小心翼翼地放入瓶中、注入透明的油液，看著小花在瓶中漂浮......整個過程會讓你忘記所有煩惱。而且手作的時候特別容易聊天，「你選這個顏色好好看！」「你幫我拿一下這個好嗎？」自然的互動就這麼發生了。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/1697009498737.jpg` },
      { type: 'text', value: `娜米悄悄說：手作活動最能看出一個人的個性——細心的、浪漫的、有創意的，都會在作品中展現出來。這是認識對方最自然的方式。我們嚴格把關每位參加者，讓你安心享受每一刻。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/195087_副本-1024x1024.jpg` },
      { type: 'text', value: `把幸福裝進瓶子裡帶回家。立即私訊戀愛小秘書報名，用一朵浮游花開啟你的浪漫故事！` },
    ],
  },
  '84866': {
    title: `盛夏微醺園遊祭`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/DSC00020_副本.jpeg`,
    content: [
      { type: 'heading', value: `夏天不談戀愛，難道要等冬天一個人發抖嗎？` },
      { type: 'text', value: `金黃夕陽倒映在河面上，祭典的燈籠點亮了浪漫的夜空，空氣中飄著美食和調酒的香氣......這不是日劇場景，這是「盛夏微醺園遊祭」！一場結合日式祭典、美食、音樂和聯誼的盛大派對，讓你在最夢幻的氛圍中遇見心動的人。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/26969576_m-678x381.jpg` },
      { type: 'text', value: `現場有專業 DJ 放音樂、有動漫歌手現場演出、有各種美味的食物和精心調配的酒水。穿著浴衣的她從你身邊走過，你手裡拿著微醺的調酒，隨著音樂搖擺——這種氛圍下，誰都會變得勇敢一點。不用刻意搭訕，只要一句「乾杯！」就能開始一段對話。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/27145814_m-2-678x381.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/4937361_m-678x381.jpg` },
      { type: 'text', value: `娜米跟你保證：這是我們最盛大、最用心的活動之一！不限年齡、不限風格，只要你是單身、想認識新朋友，都歡迎來！女生穿浴衣、和服還有額外折扣，美到冒泡的妳不來太可惜！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_7a17360046_1498207299-678x381.jpg` },
      { type: 'text', value: `夏天的夜晚太美了，不能浪費。立即私訊戀愛小秘書報名，讓我們在祭典裡一起微醺、一起心動！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f7cc39e3dd_1469691967-678x381.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/WechatIMG283-1-1024x536.jpeg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/未命名設計.png` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/DSC00044_副本-1024x684.jpg` },
    ],
  },
  '84867': {
    title: `自己做｜烘焙妳的甜心蛋糕`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/360092070_606105934960619_363698282878880428_n.jpeg`,
    content: [
      { type: 'heading', value: `想談甜甜的戀愛？先從做一個甜甜的蛋糕開始！` },
      { type: 'text', value: `一個人的週末只會叫外送配 Netflix？是時候給自己一個改變了！烘焙聯誼是我們最搶手的活動之一，每次名額都秒殺。為什麼？因為在一起做蛋糕的過程中，緊張感會自然消失，取而代之的是歡笑、協作和甜甜的氛圍。` },
      { type: 'text', value: `「我最喜歡娜米安排的手作活動，每次都讓我認識跟我一樣喜歡手作的朋友。拜託，這次務必幫我留一個位子！」——這是會員小曼的心聲，也是很多學員的心聲。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/360092070_606105934960619_363698282878880428_n.jpg` },
      { type: 'text', value: `不管你是烘焙新手還是甜點控，我們的專業主廚都會手把手教你。舒適的烘焙教室、優質的食材、還有一群和你一樣單身又有趣的人——你只需要帶著好心情來，我們幫你準備一切。從打蛋、攪拌到裝飾，每個步驟都是和身邊的人互動的好機會。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/IMG_6017-300x225.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/IMG_6020-300x225.jpg` },
      { type: 'text', value: `娜米溫馨叮嚀：來的時候穿得簡單舒適就好，記得帶上你的笑容。我們嚴格篩選每位參加者，讓你在甜蜜的氛圍中安心交友。做好的蛋糕還能帶回家，但這裡認識的人，可能會陪你更久喔！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/S__3514415-300x225.jpg` },
      { type: 'text', value: `名額有限，手刀報名！立即私訊戀愛小秘書，一起烘焙出你的甜蜜幸福！` },
    ],
  },
  '84868': {
    title: `七夕の園遊祭`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1M9A8315-1024x683-1.jpeg`,
    content: [
      { type: 'heading', value: `七夕只能在家看情侶放閃？不如自己成為故事的主角！` },
      { type: 'text', value: `內湖碼頭被點亮的那一刻，湖光與燈光交織，整個現場彷彿變成了夢幻世界。很多參與者穿著漂亮和服，讓這場聯誼活動增添了一抹日系浪漫。現場還有占卜攤位，大家都迫不及待想知道自己的愛情運勢！` },
      { type: 'text', value: `專業 DJ 的現場演出、動漫歌手的精彩表演、優雅的藝妓展示——每一個環節都讓夜晚充滿驚喜。美食與調酒更是畫龍點睛，大家在輕鬆的氣氛中自然交流。一杯酒下肚，連平時最內向的人都變得健談起來！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/06/I3HFCBUPA67NZ0A_N.png` },
      { type: 'text', value: `最感動的是，即使下起了雨，大家的熱情絲毫不減。在雨中與新認識的朋友分享一把傘，那種偶像劇般的浪漫，只有親身參與才能體會。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/275113f2cb61f4c3b4bc6d3edcb1248e-300x200.jpg` },
      { type: 'text', value: `娜米的心裡話：每一場活動都是我用心為大家規劃的。我希望在這個忙碌的時代，能為你們創造一些歡樂和心動的機會。不管你有沒有遇到「那個人」，至少你會帶走一個美好的夜晚。` },
      { type: 'text', value: `錯過了七夕沒關係，我們還有更多精彩活動等你！立即私訊戀愛小秘書，讓每一天都可以是你的情人節！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/344769750_1175439030520947_2939810061079920983_n-225x300.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_e5bafc1492_1457586652-300x169.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_ecad1ceeec_1545037467-300x200.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f567e1223d_1521796535-300x200.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/event01-1024x1024.jpg` },
    ],
  },
  '84871': {
    title: `一對一快速約會（Speed Dating）`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/event01-768x768-1.jpeg`,
    content: [
      { type: 'heading', value: `人海茫茫，你到底要滑多少個交友軟體才能遇到對的人？` },
      { type: 'text', value: `交友軟體配對了上百個人，真正約出來的不到十個，能聊超過三次的更是屈指可數。你不是不夠好，只是需要一個更有效率的方式——Speed Dating 一對一快速約會，讓你在短短幾個小時內認識多位精選對象！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/05/帶按鈕-女生會員徵男友04-林小姐新-768x1024.jpg` },
      { type: 'text', value: `我們精心挑選約會場所，氛圍輕鬆自在。每一輪你會和不同的對象面對面，透過我們設計的話題引導和「話題製造機」，你不用怕冷場，也不用擔心不知道聊什麼。短短的幾分鐘內，你就能感受到彼此之間是否有那份「化學反應」。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/06/找女友01-1.jpg` },
      { type: 'text', value: `現場還有精緻茶點，讓你在約會的空檔補充能量。最棒的是，這裡每個人都是真心想認識另一半的，不會遇到「只是來玩玩」的人！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'text', value: `娜米的保證：每位參加者都經過我們團隊的深度訪談和審核，確保素質和誠意。我們不只是幫你安排約會，更會在後續追蹤你的狀況，協助你發展關係。你不是一個人在戰鬥，娜米會一直在你身邊！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/帶按鈕圖-情境圖-男-滑手機-開心-室內-咖啡廳.jpg` },
      { type: 'text', value: `別再漫無目的地等待了。立即私訊戀愛小秘書報名，用最有效率的方式找到你的另一半！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f567e1223d_1521796535-1024x683.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/1660792332-364008c565a2b14a6ee1f14ffe6ff029-1024x576.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/10/帶按鈕圖-情境圖-男女-咖啡店.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/10/帶按鈕圖-情境圖-男女-咖啡店02.jpg` },
    ],
  },
  '84943': {
    title: `蜜糖吐司手作趣`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/04X1PF462E000D19D76B4Bpx-678x509-1.jpeg`,
    content: [
      { type: 'heading', value: `下午茶只會叫外送？親手做一份蜜糖吐司給心動的人吧！` },
      { type: 'text', value: `蜜糖吐司那華麗的外型和酥脆綿密的口感，根本是所有女孩的心頭好！但自己在家做太寂寞，在這裡和一群有趣的人一起做才對味。當你們一起細心地抹醬、一起認真地擺盤、一起期待烤箱裡的成品——那份「一起完成一件事」的甜蜜感，會讓你心裡暖暖的。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'text', value: `在專業甜點師的帶領下，每個人都能做出獨一無二的蜜糖吐司。也許你細心的擺盤動作，已經悄悄被隔壁的她注意到了。也許他遞過來的那抹微笑，就是今天最甜的調味料。鮮奶油般滑順的情感，在初秋的廚藝教室裡慢慢發酵......` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_d8b446cbef_1498466574-300x200.jpg` },
      { type: 'text', value: `娜米的溫暖保證：我們的手作活動一直是最受歡迎的系列，因為它真的能讓人在最輕鬆的狀態下認識彼此。每位參加者都經過嚴格審核，素質有保障。你只需要帶著期待的心來，甜蜜我們幫你準備好了！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f567e1223d_1521796535-1024x683.jpg` },
      { type: 'text', value: `別讓好時光空等。立即私訊戀愛小秘書報名，一起做出最甜蜜的回憶！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/event01-1024x1024.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/08/MTXX_MH20230805_211553766.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/20231014%E6%89%8B%E4%BD%9C%E8%98%8B%E6%9E%9C%E5%A1%94-1024x634.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/09/20231014手作蘋果塔-1024x634.jpg` },
    ],
  },
  '84946': {
    title: `魔女烘培｜愛情魔力再現`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1311-678x381-1.jpeg`,
    content: [
      { type: 'heading', value: `誰說聯誼一定很尷尬？用 65°C 來融化彼此的陌生感！` },
      { type: 'text', value: `夏日悠閒的午後，你走進了一間充滿奶油香氣的烘焙教室。對面站著一個有著好看笑容的人，你們彼此微微害羞——但不用怕，因為接下來的烘焙過程會讓你們的距離從一米變成零距離！` },
      { type: 'text', value: `烘焙就是最棒的破冰神器！女孩們攪拌著麵團，男孩們一匙一匙加入砂糖——感覺就像把愛情的甜蜜一次次注入彼此之間。分工合作的過程中，你們自然而然就熟絡了。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/09/1269-1024x582.jpg` },
      { type: 'text', value: `等蛋糕進烤箱的那段時間呢？就是最好的互動時間！我們設計了有趣的小遊戲——湯匙傳乒乓球，近距離的接觸讓你臉紅心跳，卻又忍不住笑出來。這就是「魔女烘培」的魔力：讓你在歡笑中不知不覺就愛上了這個下午。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/09/163970-1024x642.jpg` },
      { type: 'text', value: `娜米保證：我們的烘焙活動零壓力、超歡樂，連最害羞的人都能玩得開心。每位參加者都經過嚴格審核，讓你在甜甜的香氣中安心認識新朋友。活動結束記得留下聯絡方式，因為相遇是難得的緣分！` },
      { type: 'text', value: `讓愛情的魔力在你身上再現。立即私訊戀愛小秘書報名，一起烘焙出幸福的味道！` },
    ],
  },
  '84947': {
    title: `心心相印｜情牽護理師`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/u1836360752199427797fm30app106fJPEG.jpeg`,
    content: [
      { type: 'heading', value: `想認識護理師？在這裡，她們終於有時間跟你說話了！` },
      { type: 'text', value: `護理師是最多男生心目中理想另一半的職業——耐心、細心、有同理心。但她們工作日夜顛倒、忙到沒有自己的時間，根本沒機會認識新朋友。所以娜米特別策劃了「情牽護理師」活動，讓渴望認識護理師的優質男生，和渴望被呵護的護理師們，有一個輕鬆相遇的機會！` },
      { type: 'text', value: `活動中我們精心設計了「撩妹金句」環節——就算你平常不敢表白，也可以趁這個機會大膽寫下你的心聲！當那些充滿真心的句子被唸出來，全場女生都被撩到心花怒放。還有換桌交流和趣味互動遊戲，讓你在最自然的狀態下展現魅力。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/09/u1836360752199427797fm30app106fJPEG.jpg` },
      { type: 'text', value: `從一開始的害羞靦腆，到後來的無所不聊，你會驚訝於自己原來可以這麼大方！當配對結果揭曉的那一刻，全場歡呼——不管有沒有配對成功，你都已經踏出了最勇敢的那一步。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/09/W020210706518888899186-1024x713.jpg` },
      { type: 'text', value: `娜米的真心話：護理師們每天照顧別人，她們最需要的是一個能照顧她們的人。而你，就是那個人。我們嚴格把關每位參加者的身分和素質，讓護理師們安心赴約、放心交友。` },
      { type: 'text', value: `心動不如行動。立即私訊戀愛小秘書報名，你的白衣天使正在等你！` },
    ],
  },
  '84948': {
    title: `天生絕配｜桌遊對對碰`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1262-768x646-1.jpeg`,
    content: [
      { type: 'heading', value: `情侶之間最需要什麼？不是浪漫，是默契！` },
      { type: 'text', value: `在一場桌遊中，你可以看到一個人最真實的樣子：他是冷靜分析型還是衝動行動派？她是溫柔配合型還是競爭心爆棚？這些在咖啡廳裡聊一百次天都看不到的特質，在桌遊裡幾分鐘就暴露無遺！` },
      { type: 'text', value: `「桌遊對對碰」的厲害之處就在：遊戲才剛開始，大家就已經笑成一團了。完全不用擔心尷尬，因為當你們為了輸贏腦力全開、為了一張牌爭得面紅耳赤的時候，陌生感早就被拋到九霄雲外了！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/09/1262-1024x861.jpg` },
      { type: 'text', value: `來參加的女生都超活潑，活動還沒開始就聊開了！男生們一開始可能比較害羞，但一拿起牌就變了一個人，專注的眼神、認真的表情——帥到不行。遊戲空檔是好感升級的最佳時段，聊天完全零距離！贏了還有獎品，輸了也有驚喜，重點是你們已經變成朋友了。` },
      { type: 'text', value: `娜米保證：桌遊活動的歡樂指數爆表，很多學員參加完都意猶未盡，還互相約下次要一起來！我們嚴格篩選每位參加者，讓你在最嗨的氣氛中交到最棒的朋友。` },
      { type: 'text', value: `你的最佳拍檔正在等你。立即私訊戀愛小秘書報名，一起在遊戲中找到你的「天生絕配」！` },
    ],
  },
  '84949': {
    title: `鮭魚料理｜吃心絕對`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1260-768x472-1.jpeg`,
    content: [
      { type: 'heading', value: `會煮飯的人，在約會市場上就是大殺器！` },
      { type: 'text', value: `想贏得心儀對象的心？先搞定他/她的胃！但你不用是五星主廚，只要願意捲起袖子一起下廚，就已經加分到爆了。鮭魚料理聯誼就是讓你「用美食撩人」的最佳舞台！` },
      { type: 'text', value: `在帥氣主廚的指導下，就算你是廚房小白也能做出專業水準的料理。挑選食材時大家圍在一起交流，超多隱藏的廚藝高手！主廚還沒講完，有些人就已經迫不及待開始料理了。看到隔壁的人需要幫忙？主動伸出手——這就是最自然的搭訕方式。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/10/1260-1024x629.jpg` },
      { type: 'text', value: `料理完成後，還有品酒師教你挑選搭配的白酒。一邊享用自己做的鮭魚料理，一邊品味美酒，一邊和新認識的朋友聊天——這就是人生啊！活動最後每個人都獲頒「廚師認證」，大家做出來的料理都超成功，成就感滿滿！` },
      { type: 'text', value: `娜米跟你說：料理聯誼之所以這麼受歡迎，就是因為「一起做飯」天生就帶有親密感。我們嚴格審核每位參加者，從食材到環境到對象，全部幫你把關！` },
      { type: 'text', value: `下一道菜，為你的愛情而做。立即私訊戀愛小秘書報名，一起用美食征服彼此的心！` },
    ],
  },
  '84950': {
    title: `Ｋ歌派對｜情聲綿綿`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/YWB32VA1BFO55VQW2-1-768x477-1.png`,
    content: [
      { type: 'heading', value: `愛，讓我們用歌聲串起陌生的彼此！` },
      { type: 'text', value: `不會聊天沒關係，會點歌就行！K歌聯誼最神奇的地方就是：一拿起麥克風，再內向的人都會變成另一個人。那個平常不太說話的他，一開口唱歌居然超好聽？那個看起來文靜的她，居然是隱藏的嘻哈Queen？驚喜太多了！` },
      { type: 'text', value: `活動一開始大家都還有點靦腆，但第一首歌唱完，全場氣氛就炸了！帥哥的渾厚嗓音讓女生聽傻，美女的天籟歌聲讓男生全部當啦啦隊。到了後半場，大家已經不只唱歌了——直接下舞池跳舞！男女眼神交會的瞬間完全觸電，全場起哄的同時，愛情的火苗已經開始燃燒。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/03/%E8%9E%A2%E5%B9%95%E5%BF%AB%E7%85%A7-2018-12-25-%E4%B8%8B%E5%8D%885.41.28-1.png` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f567e1223d_1521796535-1024x683.jpg` },
      { type: 'text', value: `娜米保證：K歌派對是我們最嗨的活動之一！現場氣氛歡樂到你會忘記時間。每位參加者都經過嚴格審核，帥哥美女齊聚，讓你在歌聲中找到那個「聽懂你歌聲」的人。` },
      { type: 'text', value: `你的下一首情歌，要唱給誰聽？立即私訊戀愛小秘書報名，讓歌聲成為你們的紅線！` },
    ],
  },
  '84951': {
    title: `多肉植物｜愛在蔓延時`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/YWB32VA1BFO55VQW2.png`,
    content: [
      { type: 'heading', value: `療癒性的植栽，你身邊的人都不懂？來這裡找到懂你的人！` },
      { type: 'text', value: `如果你也是那種會對著盆栽說話、幫多肉取名字的人，那恭喜你——這場活動會讓你遇到一群跟你一樣「有愛」的人！養多肉就像談戀愛，需要耐心、需要細心，更需要一個願意跟你一起照顧小生命的人。` },
      { type: 'heading', value: `學員們開始選位子了` },
      { type: 'text', value: `一入座，大家就開始分享自己平常在家種植的盆栽經驗，原來每個人對植栽都超有熱忱！從老師專業講解多肉品種和換盆技巧開始，到大家動手量測、裝土、扦插——每個環節都充滿歡笑和交流。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/10/1238-1024x652.jpg` },
      { type: 'heading', value: `多肉盆栽自己動手來` },
      { type: 'text', value: `遇到困難也不怕，旁邊的導師和同伴都會互相幫忙。當你和心儀的她一起完成一個多肉盆栽，那種成就感和甜蜜感，會讓你帶著微笑回家。記得好好培育這個小生命——每次澆水的時候，就會想起那天認識的人。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/10/YWB32VA1BFO55VQW2.png` },
      { type: 'text', value: `娜米的溫暖叮嚀：多肉活動就像多肉本身——小小的、療癒的、卻充滿生命力。我們嚴格把關每位參加者，讓你在最溫馨的氛圍中交到真心朋友。` },
      { type: 'text', value: `讓愛和多肉一起蔓延生長。立即私訊戀愛小秘書報名，種下你們的幸福盆栽！` },
    ],
  },
  '84955': {
    title: `烹然心動｜回鮭愛的原點`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1266-678x381-1.jpeg`,
    content: [
      { type: 'heading', value: `想抓住她的心？先抓住她的胃！` },
      { type: 'text', value: `約會只會帶對方去餐廳？如果你能親手做一道菜給她，好感度直接翻倍！不會料理也完全沒關係——現場有專業主廚 carry 你，從切菜到擺盤，手把手帶你完成一道漂亮的鮭魚料理。` },
      { type: 'text', value: `料理的過程就是最棒的互動時間：你幫她拿食材、她幫你調味，互相幫忙完成這道菜的默契，比任何聊天都來得有溫度。做完之後一起享用，品嚐彼此的成果，那種開心的感覺比去高級餐廳還幸福！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/09/1266-1024x579.jpg` },
      { type: 'text', value: `活動結束還有精美小禮物送給你，讓這份美好的記憶更加完整。很多學員都說，這是他們最喜歡的活動類型——因為一起做飯真的會讓人瞬間變得很親近！` },
      { type: 'text', value: `娜米保證：所有參加者都經過嚴格審核，食材新鮮、環境舒適、對象優質。你只需要帶著一顆願意嘗試的心來就好！` },
      { type: 'text', value: `回到愛的原點，從一道料理開始。立即私訊戀愛小秘書報名，一起烹出心動的感覺！` },
    ],
  },
  '84956': {
    title: `遊艇派對｜海上的浪漫`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1307-678x381-2.jpeg`,
    content: [
      { type: 'heading', value: `在陸地上脫不了單？那就出海吧！` },
      { type: 'text', value: `你有想過在遊艇上認識另一半嗎？海風輕輕吹過、夕陽灑在海面上、手裡拿著冰涼的飲料——在這種浪漫到不行的場景裡，連平常最害羞的人都會變得大方。遊艇派對不只是聯誼，更是一場讓你永生難忘的海上冒險！` },
      { type: 'text', value: `船上設有 KTV，大家可以自由歡唱。還有趣味派對小遊戲，讓氣氛嗨到最高點！精心準備的小點心和飲品，在主持人專業的帶領下——「拿起你的飲料！舉起你的雙手！準備——乾杯！！」這一刻，太平洋充滿了你們的歡笑聲。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/04/1307-1024x577.jpg` },
      { type: 'text', value: `遊艇上的空間剛剛好，不會太擠也不會太散。站在甲板上和她聊天，海風吹亂了她的頭髮，你幫她撥到耳後——這種偶像劇場景，在遊艇上隨時都可能發生。有人在船上遇到了唱歌超好聽的「被工程耽誤的歌手」，有人聞到了曖昧的味道......你呢？` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/04/164229-1024x583.jpg` },
      { type: 'text', value: `娜米跟你保證：遊艇派對是我們最高規格的活動之一，安全、品質、氛圍都是頂級。每位參加者都經過嚴格審核，讓你在最浪漫的海上之旅中安心交友。` },
      { type: 'text', value: `上船吧，你的愛情正在等你出航。立即私訊戀愛小秘書報名，和命中注定的人一起乘風破浪！` },
    ],
  },
  '84959': {
    title: `水上騎馬打仗 清涼刺激的泳池Party`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/img-2-426x351-1.jpeg`,
    content: [
      { type: 'heading', value: `夏天太熱了？跳進泳池裡脫單吧！` },
      { type: 'text', value: `盛夏的酷熱讓人只想泡在水裡，但一個人去泳池也太無聊了！如果是和一群帥哥美女一起水上騎馬打仗呢？男生背女生進攻、閃躲對方的潑水攻勢、左躲右閃把握時機——這根本是夏天最熱血的聯誼方式！` },
      { type: 'text', value: `泳池派對最棒的地方就是：在水裡，所有的拘謹和距離感都被沖走了。你們一起歡笑、一起尖叫、一起嬉戲，比任何聯誼活動都更容易「破防」。當她坐在你肩上一起作戰的時候，那種信任感和親密感，是坐在餐廳裡永遠不可能有的！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f567e1223d_1521796535-1024x683.jpg` },
      { type: 'text', value: `娜米保證：泳池活動安全第一，全程有專業工作人員在旁。每位參加者都經過實名認證和嚴格審核。你只需要帶著泳衣和一顆玩心來，清涼的快感和心動的瞬間，我們幫你一次搞定！` },
      { type: 'text', value: `這個夏天，不要只是看別人曬恩愛。立即私訊戀愛小秘書報名，一起跳進幸福的泳池吧！` },
    ],
  },
  '84962': {
    title: `第六感手拉坯`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/163966-678x381-1.jpeg`,
    content: [
      { type: 'heading', value: `如果一塊陶土可以塑出藝術品，一場手拉坯也可以成就你的愛情！` },
      { type: 'text', value: `看過《乏乞乏》（Ghost）裡那個經典的手拉坯畫面嗎？兩個人的手在旋轉的陶土上交疊，浪漫到不行！現在，你也有機會體驗這個場景——而且對面坐的是真人，不是螢幕！` },
      { type: 'text', value: `一到現場，大家都充滿好奇地聚在一起了解手拉坯。分組後由指導人員教學，你們各自創作、互相觀摩、互相吐槽彼此的「抽象藝術品」。在自己的作品中添加兩人的默契和笑聲——這才是最珍貴的紀念品。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2019/04/163966-1024x576.jpg` },
      { type: 'text', value: `娜米小語：手作活動最能看見一個人的個性。在旋轉的陶輪前，你會看到他的專注、她的創意、還有你們之間的默契。所有參加者都經過嚴格審核，讓你在最藝術的氛圍中邂逅最對的人。` },
      { type: 'text', value: `心動了嗎？立即私訊戀愛小秘書報名，用雙手塑造你的浪漫故事！` },
    ],
  },
  '84964': {
    title: `非誠勿擾｜快速換桌`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/164332-768x502-1.jpeg`,
    content: [
      { type: 'heading', value: `一場活動認識十個人？快速換桌讓你不再「只認識隔壁那一位」！` },
      { type: 'text', value: `很多人參加大型聯誼的煩惱是：整場只跟坐隔壁的人聊天，其他人根本沒機會認識。「非誠勿擾」快速換桌完美解決了這個問題！每隔一段時間就換位子，讓你和現場每個人都有面對面交流的機會。` },
      { type: 'text', value: `活動場地選在浪漫的高級婚宴會館，男女面對面深入了解彼此的愛情觀和理想條件。內向也完全沒問題！工作人員會安排你入座，主持人會帶大家自我介紹和愛情宣言，還有默契小遊戲讓你臉紅心跳。每一個環節都是愛神來訪的徵兆！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2018/10/164332-1024x669.jpg` },
      { type: 'text', value: `娜米保證：「非誠勿擾」的參加者都是認真想找另一半的人，我們嚴格審核每位報名者的身分和誠意。在這裡，你不會遇到「來玩玩而已」的人，只有和你一樣真心尋找幸福的靈魂。` },
      { type: 'text', value: `你的命中注定也許就在隔壁桌。立即私訊戀愛小秘書報名，讓緣份不再錯過！` },
    ],
  },
  '84966': {
    title: `巧克力情人夢`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/art.jpeg`,
    content: [
      { type: 'heading', value: `愛情來之前，你需要一點聰明、一點幽默、一點心動。` },
      { type: 'text', value: `你有沒有遇過這種情況：明明對她有好感，卻不知道怎麼讓她也注意到你？或是聊天總是冷場，氣氛怎麼都暖不起來？「巧克力情人夢」用精心設計的默契遊戲來解決你的所有困擾！` },
      { type: 'text', value: `活動一開始，主持人會將男女分開進行破冰遊戲，讓你在輕鬆的氛圍中認識每個人。了解彼此之後，進入最刺激的「默契大考驗」——看看你和誰的心電感應最強！透過有趣的互動話題和配對遊戲，你會發現認識新朋友原來這麼有趣。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ChMkJ1gixK6IMQ7ZAAGcA8w2nx4AAXmlQOwmycAAZwb802.jpg` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ChMkJ1gixK6IMQ7ZAAGcA8w2nx4AAXmlQOwmecAAZwb802.jpg` },
      { type: 'text', value: `娜米跟你保證：這場活動的節奏明快、氣氛歡樂，連最慢熱的人都會被帶動起來！每位參加者都經過嚴格審核，讓你在甜蜜的巧克力氛圍中安心交友。` },
      { type: 'text', value: `讓巧克力幫你傳情，讓默契幫你牽線。立即私訊戀愛小秘書報名，你的情人夢就要成真了！` },
    ],
  },
  '84967': {
    title: `阿根廷探戈`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1336-768x402-1.jpeg`,
    content: [
      { type: 'heading', value: `不會說話沒關係，讓身體替你表白！` },
      { type: 'text', value: `你是不是覺得交朋友最難的就是「不知道聊什麼」？那就別聊了——跳舞吧！音樂和舞蹈是人類最原始的語言，不需要絞盡腦汁想話題，你們之間的舞步就能讓兩個人很快熟悉起來。而且探戈那種貼近、對視、進退之間的默契，浪漫指數根本爆表！` },
      { type: 'text', value: `全程只要一小時教學，就算你從來沒跳過舞也沒問題！我們有超強的師資陣容，不怕肢體不協調，只怕你不敢走出第一步。很多學員跳完都說：「原來跳舞這麼好玩！」更重要的是，換舞伴的環節讓你和現場每個人都有互動機會。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_f567e1223d_1521796535-1024x683.jpg` },
      { type: 'text', value: `當你和她四目交接、隨著音樂搖擺的時候，那份心動是真實的。熟悉了以後，大方邀她跳一支難忘的舞——這就是探戈聯誼最迷人的地方。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'text', value: `娜米保證：這場活動專業、安全、充滿浪漫氣息。每位參加者都經過嚴格審核，讓你在優雅的舞步中安心認識新朋友。` },
      { type: 'text', value: `下一支舞，為你心動的人而跳。立即私訊戀愛小秘書報名，讓探戈成為你們愛情的序曲！` },
    ],
  },
  '84968': {
    title: `美味料理｜幸福好味道`,
    heroImage: `/images/original/shesay.com/wp-content/uploads/2023/11/1309-678x381-1.jpeg`,
    content: [
      { type: 'heading', value: `幸福是什麼味道？一起做的料理告訴你！` },
      { type: 'text', value: `在交友軟體上聊一百句，不如在廚房裡一起做一道菜。當你們肩並肩站在料理台前，從自我介紹開始，到一起切菜、一起調味、一起等待出鍋——每一個步驟都是拉近距離的契機。不會料理也完全沒關係，有專業主廚手把手教你！` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2018/10/1309-1024x577.jpg` },
      { type: 'text', value: `做完料理後一起用餐，是最放鬆的聊天時間。品嚐彼此的手藝、分享對美食的喜好、聊聊生活中的小事——不知不覺你們就從陌生人變成朋友了。活動結束還有精美小禮物和交換聯絡方式的時間，讓這段緣份延續下去。` },
      { type: 'image', value: `https://ek21.com/dating/wp-content/uploads/2023/07/ev_cd416212ab_1450500908-1024x683.jpg` },
      { type: 'text', value: `娜米保證：料理聯誼一直是我們最溫馨的活動系列。食材新鮮、環境舒適、每位參加者都經過嚴格審核。你只需要帶著一顆願意嘗試的心來，幸福的味道我們幫你調好了！` },
      { type: 'text', value: `幸福的味道，一起做才好吃。立即私訊戀愛小秘書報名，用一道料理開啟你的愛情故事！` },
    ],
  },
};
